export {ReactComponent as Amazon} from './amazon.svg'
export {ReactComponent as Bookwalker} from './bookwalker.svg'
export {ReactComponent as Ebookjapan} from './ebookjapan.svg'
export {ReactComponent as Mangaupdates} from './mangaupdates.svg'
export {ReactComponent as Anilist} from './anilist.svg'
export {ReactComponent as Animeplanet} from './animeplanet.svg'
export {ReactComponent as Kitsu}from './kitsu.svg'
export {ReactComponent as Myanimelist} from './myanimelist.svg'
